baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = "dalamarsblog"
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Daniel Sobrado"
  subtitle    = ""
  copyright   = "Â© 2018"

  cover       = "img/blog-cover.jpg"
  description = "Personal Blog on Data Science, Big Data and Software Development."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""
  
  publishDir = "docs"

  twitterName = "DalamarBlog"
  fbName = "j.daniel.sobrado"
  githubName = "danielsobrado"
  linkedinName = "dsobrado"
  mediumName = "dalamar01977"

  logo = "/img/daniel-logo.png"
  orgName = "Daniel Sobrado"
  orgWebsite = "https://www.danielsobrado.com"
  orgDescription = "Personal Blog on Data Science, Big Data and Software Development."

  showSupport = true

  author = "Daniel Sobrado"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Abu Dhabi, UAE"
  authorWebsite = "https://github.com/danielsobrado"
  authorDescription = "Daniel Sobrado"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Data Science"
  url = "/tags/datascience/"
  weight = 100

[[menu.main]]
  name = "Others"
  url = "https://google.com/"
  weight = 95

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99


